name: "EcoFlow SHP3 Bridge"
version: "1.0.1"
slug: "ecoflow_shp3_bridge"
description: "MQTT bridge for EcoFlow Smart Home Panel 3 and Delta Pro Ultra"

startup: application
boot: auto
init: false
host_network: true

arch:
  - amd64
  - aarch64

map:
  - share:rw
  - addon_config:rw

options:
  mqtt_host: core-mosquitto
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_pass: ""
  update_interval: 5

schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str?
  mqtt_pass: str?
  update_interval: int
